RedHat-Israel/ROSE

- rtp/client/car.py
- rtp/client/world.py
- rtp/common/core.py
- rtp/server/game.py
- rtp/server/player.py
We added recently a Point class for holding player position, assuming
that it will clean up the code, but it only made it worse. Now objects
keeping a position have x and y properties.
> Remove unneeded Point class

- README
- rtp/server/game.py
- rtp/server/score.py
- rtp/server/score_test.py
Scoring is the most tricky and badly implemented part of the game, and
we like to make significant logic changes. This patch adds tests
covering the current behavior, to make it easier to make the needed
changes later.
To make scoring more testable, scoring moved to a new module, so we do
not have to create a game object for testing scoring.
> Add scoring tests

- rose/common/config.py
- rose/server/game.py
- rose/server/player.py
- rose/server/score.py
- rose/server/score_test.py
Signed-off-by: Yaniv Bronhaim <ybronhei@redhat.com>
> Removing life and use score

- rose/common/config.py
- rose/server/score.py
- rose/server/score_test.py
Signed-off-by: Yaniv Bronhaim <ybronhei@redhat.com>
> Adding score prefix

- rose/server/score.py
1. to be able to pickup penguin we should be able to discover 2
lines of obstacles ahead.
for example:
- the car located at (x,y)
- the next penguin located at(x-1, y-2)
to pickup this penguin you should return left then pickup
2. also get 10 points for each movement forward otherwise there is
a situation of player which cross the finish line but the other
player which behind the finish line has more points.
> Fixed the score and limit the forward until y=2

- rose/server/game.py
- rose/server/main.py
- rose/web/index.html
These patches expose the server game rate in the web interface and allow changing the rate with a single click.
The web interface is still raw html, I will add basic CSS in the next patches.
@emesika, @bronhaim, please review.
> Web admin: change game rate from the web intreface

- rose/server/score_test.py
Signed-off-by: Yaniv Bronhaim ybronhei@redhat.com
> fix part of tests and disable parts of those I didn't understand

- .travis.yml
- README.md
- pytest.ini
- requirements.txt
- Add standard requirements.txt to simplify installation
- Simplify testing
- Add travis ci intergation
Fixes #162.
@emesika, @rollandf please review.
> Run the tests in travis

- rose/server/score_test.py
Disabling tests means we will never fix this. Let the test fail until
someone has time to fix them.
> Enable failing tests disabled in recent test fix

- rose/client/game.py
- rose/client/track.py
- rose/server/game.py
- rose/server/track.py
Change the format of the state messages to be easier to debug, using list of dicts.
> Make state messages easier use and debug

- rose/server/main.py
- rose/server/net.py
> Server cleanup

- rose/web/game.js
> Add player name label to cars in web UI

- .gitignore
- Pipfile
- README.md
Add pipenv's Pipfile and update README.md to reflect thus support
Issue #188
> Add pipenv

- .travis.yml
- examples/none.py
- examples/random-driver.py
- requirements.txt
- rose/client/car.py
- rose/client/track.py
- rose/client/world.py
- rose/common/actions.py
- rose/common/error.py
- rose/common/message.py
- rose/common/obstacles.py
- rose/server/game.py
- rose/server/net.py
- rose/server/player_test.py
- rose/server/score.py
- rose/server/score_test.py
Closes #223 
I was unable to figure out git so I did the work required on this new branch. The only parts not resolved are the two print statements to fail as you said they would be resolved in #216
> add flake8 to travis-ci

- .flake8
- .travis.yml
- Pipfile
- README.md
- rose/server/score.py
- Add it to Pipfile
- Add .flake8 configuration file
- Fix last pep8 violations
- Update developer documentation
> Complete flake8 integration

- README.md
- docs/code-of-conduct.md
Add Code of Conduct (fixing #245 )
> Add code of conduct

- rose/common/message.py
> Modernize imports in rose.common package

- rose-admin
- rose/client/main.py
> Replace print with logging in rose-admin and rose.client

- setup.py
> Add comment to generated requirements.txt

- docs/_config.yml
- docs/development.md
- docs/examples/driver.md
- docs/index.md
> Add basic docs directory for GH pages

- README.md
Fixed some grammar issues, added links to events and two new recent resources that were missing
> Additions to the "talks" section

- README.md
Add Laura Novich article to the "Talks and presentations" section
> Add link to article in opensource.com

- README.md
She spells it "Kenneth", with two Ns.
> Fix typo Keneth->Kenneth in Miki Kenneth's name

- docs/course_materials/control_structures.html
- docs/course_materials/meet_linux.html
- docs/meet_linux.md
- Some minor changed in the "if" sections
- Add an empty "Meet Linux" page
- Add content for functions
> Add Functions content

- docs/course_materials/homeworks.md
- docs/course_materials/variables_data_types.html
Note that  there are no direct link to thins page in purpose
See how it renders here:
https://rollandf.github.io/ROSE/course_materials/homeworks.html#/
>  Add homeworks page

- docs/course_materials/control_structures.html
- docs/course_materials/media/presentations.css
- docs/course_materials/variables_data_types.html
Remove unneeded slide_header div
> Python content - remove slide_header div

- README.md
Without it, they don't use the virtualenv and don't find dependencies:
```
$ ./rose-server
Traceback (most recent call last):
File "./rose-server", line 3, in <module>
from rose.server import main
File "/home/bpaskinc/ROSE/rose/server/main.py", line 4, in <module>
from twisted.internet import reactor
ImportError: No module named twisted.internet
```
> README: Execute commands under pipenv

- docs/game.md
@rollandf @sleviim please review and add content
> Start game materials page

- rose/web/game.js
Disabling the music in the browser until we are able to mute it.
See issue #295
> Disable sound in the browser

- docs/course_materials/control_structures.html
- docs/course_materials/homeworks.md
- docs/course_materials/modules_packages.html
- docs/course_materials/variables_data_types.html
- docs/game.md
> Modify presentations' content from python2 to python3

- docs/course_materials/variables_data_types.html
This patch adds an example of using strings values from input, and
casting the input's value to an int.
> Using input on python2

- docs/course_materials/compound_data_types.html
- docs/course_materials/control_structures.html
- docs/course_materials/exceptions.html
- docs/course_materials/functions.html
- docs/course_materials/linux_intro.html
- docs/course_materials/modules_packages.html
- docs/course_materials/python_intro.html
- docs/course_materials/variables_data_types.html
Tags formatting shouls help with editing the presentations
> Use tabs on html tags formatting

- docs/course_materials/python_intro.html
- Changed syntax to Python3
- Added a slide for print() function
- Added a slide for comments in python
- Changes the exercise to contain a comment as well
> Edited the Python introduction presentation

- rose/web/game.css
- rose/web/game.js
- rose/web/index.html
Hi, these are the changed I've made after looking at [issue:295](https://github.com/RedHat-Israel/ROSE/issues/295) and [issue:231](https://github.com/RedHat-Israel/ROSE/issues/231).
- Music is not playing automatically when the page loads.
- Can be toggled via UI or JS API.
> Add music control to UI

- docs/course_materials/compound_data_types.html
* Performed improvements according to the list of suggested changes.
* Added some information regarding data types.
* Used the correct CSS style for proper Python code highlighting.
I've added some information and also slightly changed some wording.
Please see if this is up for your liking and if the additional information doesn't add extra bloat to the course.
> Extend Compound Data Types Presentation

- docs/course_materials/exercises/01_Linux/class_exe.md
- docs/course_materials/linux_intro.html
- Use <br> to break long paragraph sentences.
- Use <b> for emphasizing directories names (also in the exercise).
- Change some capital/small letters as needed.
- Remove the sl example from sudo dnf install.
@shiramax, please approve
> Add few more changes to the linux_intro presentation

- docs/course_materials/compound_data_types.html
- Edit some examples to meet python3 format
- Some syntax formatting
> Edit the compound_data_types presentation

- docs/course_materials/control_structures.html
- Edit some alignments
- Marked printed output with #
> Edit the control_structures presentation

- docs/course_materials/exercises/02_Python_intro/class_exercise_1.md
- docs/course_materials/python_intro.html
In case the students have version < 3, some functions might not work
well.
> Use python3 for running python script example

- docs/course_materials/exercises/01_Linux/class_exercise_2.1.md
- docs/course_materials/exercises/01_Linux/class_exercise_2.2.md
- docs/course_materials/exercises/01_Linux/homework_1.md
- docs/course_materials/exercises/03_Variables_and_datatypes/class_exercise_1.md
- Use bold for directory names
- change syntax to python md
> Edit some exercises files

- docs/course_materials/exercises/03_Variables_and_datatypes/class_exercise_1.md
- docs/course_materials/exercises/03_Variables_and_datatypes/class_exercise_2.md
- docs/course_materials/exercises/03_Variables_and_datatypes/homework_Strings.md
- docs/course_materials/exercises/03_Variables_and_datatypes/homework_Variables.md
- docs/course_materials/variables_data_types.html
Create changes in the Variables_data_types slides
Fix the doc of Variables_data_types Homework
Fix the doc of Variable_data_type class exercise
> Adding changes in Variables_data_types slides, class exercises and homework

- docs/course_materials/exercises/03_Variables_and_datatypes/homework_strings.md
@sleviim please review and merge.
> Fix wrong-type apostrophe

- rose/server/main.py
x2 - E501 line too long
x1 - W293 blank line contains whitespace
@sleviim please review.
> Fix flake8 errors

- docs/course_materials/exercises/03_Variables_and_datatypes/homework_strings.md
Fixed a function name:
`length()` to `len()`
I guess it may have confused students.
> Strings homework - Fixed a function name

- README.md
Changes paths of the Readme to fit our new pipenv environment
> Rewrite instructions for pipenv in the Readme file

- .travis.yml
- Pipfile
- README.md
Hi @shiramax , 
Added a test for .md files using [jupyterlab/pytest-check-links](https://github.com/jupyterlab/pytest-check-links).
Since there were some wrong links in the revel directories, added an ignore in the test script for the directory.
Updated dev section in the Pipfile and added the test to script section in travis.yml
> Added a test for .md links

- examples/README.md
- rose/server/score.py
Fixed the punishment score so it reduces 10 points
Removed extra forward step for pickup
Added an if statement for the case of unmagical obstacles
Checked the scoring between the drivers after the fix, seems more fair.
There is a notable difference between a driver that tries to follow the rules and a random one.
> Updated the scoring method

- docs/course_materials/compound_data_types.html
Edit the example to be consistent with the one above it
> compound_data_types: edit example

- rose/server/score_test.py
@sleviim , @shiramax Fixed the score_test.py according to the changes in the scoring method.
All test passed.
> Fixed the test according to the new score system.

- docs/course_materials/exceptions.html
- docs/course_materials/exercises/07_Exceptions/class_exercise_1.md
- docs/course_materials/exercises/07_Exceptions/homework.md
Adding changes and homework for Exceptions lesson:
* Adding new directory called "07_Exceptions" with class exercise and homework
* Changed the class exercise page
> Adding changes and homework for Exceptions lesson.

- classroom/README.md
- classroom/connect_service.py
- classroom/content_edit.py
- classroom/rose_class.py
Hi @shiramax , added the option for adding topics and retrieving existing ones.
Also updated the README accordingly.
Should I continue to adding ClassWork functionality?
> ClassRoom API - Adding topic

- docs/course_materials/exercises/04_Compound_data_types/homework_list.md
- docs/course_materials/exercises/test_exercises/04_Compound_data_types/test_homework_dictionaries.py
- docs/course_materials/exercises/test_exercises/04_Compound_data_types/test_homework_lists.py
- docs/course_materials/exercises/test_exercises/pytest.ini
Hi @sleviim ,
It's the second part of the long pr.
This one includes only the tests for lesson 4 : lists and dictionaries.
> Created tests for dictionay and list homework

- docs/course_materials/exercises/test_exercises/conftest.py
- docs/course_materials/exercises/test_exercises/how_to_add_python_tests.md
- how_to_check_student_exercises.md
Hi @sleviim ,
It's the first part of the long pr.
This one includes only the ammended test logic for students homework.
> Updated the test homework method and docs

- docs/course_materials/exercises/03_Variables_and_datatypes/homework_strings.md
- docs/course_materials/exercises/test_exercises/03_Variables_and_datatypes/test_homework_strings.py
- docs/course_materials/exercises/test_exercises/03_Variables_and_datatypes/test_homework_variables.py
- how_to_check_student_exercises.md
Hi @sleviim ,
It's the third part of the long pr.
This one includes only the ammended tests for lesson 3 : strins and variables.
> Updated the tests to the new test method

- Pipfile
Hi @sleviim , found the solution for the conflict when tring to run docker for dev.
Hope it will be useful.
> fixes dev docker #427

- rose-admin
- rose/client/game.py
- rose/client/main.py
- rose/server/game.py
- rose/server/score.py
Ref: https://github.com/RedHat-Israel/ROSE/pull/476/files#r1306497974
Follow up for score logic cleanup, separate PR #476 to python2 cleanup and score logic cleanup.
> Cleanup python2 six and imp libraries
