examples/README, rtp/client/track.py, rtp/client/world.py, rtp/server/game.py, rtp/server/track.py
For testing, we need a way to set obstacles at non-random location and
check if the player action is handled correctly.
To unify track interface names, get_obstable() was renamed to
get() in Track and World.
Get method will be more correct when we expose other cars location using
World.get().
=> Add Track.set() method

rtp/common/config.py, rtp/server/player.py, rtp/server/player_test.py, rtp/server/score.py, rtp/server/score_test.py
Prvevsiously we would sort players by their y value and response time,
so leading/faster players took a position before other players, causing
other players to move back. This make the game too random, so the first
player getting a penguin (randomly) wins.
Now we let players driving it their lane to choose the next position,
and other players trying to pick other player penguin loose and moved
back.
=> Prefer players in their own lane when resolving collisions

setup.py
The previous name was creating a package name with an unusual name
including spaces in the package name.
=> Rename setup name to lowercase

rose/common/obstacles.py, rose/server/track.py
We used to generate one random obstacle per row at a random cell. This
created unfair conditions, causing random driver to win even if the
other driver code is equal or better.
Now we generate the same obstacle for both drivers. To make the track
more interesting, we randomize the cell for each lane.  To make the
track less crowded, NONE is now one of generated obstacles, creating an
empty row when selected.
Testing same driver code (not considering the lane yet) we see more fair
results.
This address #131
=> More fair obstacle generation

rose/server/score.py, rose/server/score_test.py
We used to sort players by their in_lane status before processing
actions. This lead to possible wrong collision resolving, where a player
which is not in its lane *after* the turn won the collision.
Now we first handle RIGHT and LEFT actions, moving players into place,
and only then we sort players by in_lane status, and handle other
actions. If after the turn a player is not in its lane, it will lose a
collision with other player.
=> Fix scoring when turning into other player lane

rose/common/config.py, rose/server/score.py, rose/server/score_test.py
Instead of using penguin_catch we use move_forward.
Omit unnessecery_action_score.
Decrease score after collision.
Tests fix to fit the new score code.
Signed-off-by: Yaniv Bronhaim <ybronhei@redhat.com>
=> fix score details

rose/server/main.py
Solves #148 
Here an example of the output :
add player: Random Driver lane: 0 car: 3
Error handling message: Player exists: Random Driver
=> Print error message in server when adding an existing player

README.md
We renamed the file recently but it was using rst syntax. Github knows
how to render it, but we should use proper syntax.
=> Convert readme to markdown

rose/server/score_test.py
The tests failed after commit 49159b40aa1a (Fixed the score and limit
the forward until y=2), adding bonus for on every cycle.
This broke unsafe tests that used the same player in a loop to test
multiple actions. Use py.mark.parametrize() to generate separate test
for each case, each using a new player instance.
Fixes #150.
=> Fix failing tests

.coveragerc
Add .coveragerc file omitting the tests modules. Now coverage show the
true value - 20%.
---------- coverage: platform linux2, python 2.7.13-final-0 ----------
Name                       Stmts   Miss  Cover
----------------------------------------------
rose/__init__.py               0      0   100%
rose/client/__init__.py        1      1     0%
rose/client/car.py            32     32     0%
rose/client/component.py       4      4     0%
rose/client/dashboard.py      36     36     0%
rose/client/end.py            11     11     0%
rose/client/finish.py         17     17     0%
rose/client/game.py           87     87     0%
rose/client/main.py           51     51     0%
rose/client/splash.py         11     11     0%
rose/client/track.py          42     42     0%
rose/client/world.py …
=> Omit test modules in coverage report

rose/client/car.py, rose/client/game.py, rose/client/track.py
Some imports and instance variables are not needed now in the client
package, after pygame was removed in #219.
=> Remove last traces of pygame

rose/client/car.py, rose/client/game.py
This pull requests removes the two parameters `x` and `y` from the constructor of the Car class since those were found to be useless in #227.
=> Remove useless parameters from Car.__init__

.travis.yml
Travis fails now when trying to lock the packages. Avoid the unneeded
locking step and use the Pipfile instead.
Fixes #228.
=> Avoid Pipfile.lock in travis

.travis.yml
In travis we are already running inside a virtual environment, so there
is no need for system pip management.
Here is an example run with this patch:
$ pipenv install --dev --skip-lock
Courtesy Notice: Pipenv found itself running within a virtual
environment, so it will automatically use that environment, instead of
creating its own for any project.
Installing dependencies from Pipfile…
🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 6/6 — 00:00:11
=> Remove --system option in travis

README.md, docs/development.md, docs/examples/driver.md, examples/README, examples/none.py, examples/random-driver.py, rose/client/main.py
This PR adds support for providing server address as an optional parameter from command line.
The server address in the 'Driver' code is not needed. If present it will be ignored.
When running the rose-client , the 'server-address' parameter provided will be used as FQDN/IP address of the server that the client will connect to.
If it is not provided localhost (127.0.0.1) will be used.
In addition, the URL of the game is printed in the console.
This support also enable the use of compiled drivers with any server.
Here is the help output of the command:
```
./rose-client -h
usage: rose-client [-h] [--server-address SERVER_ADDRESS] driver_file
ROSE Client
positional arguments:
driver_file           The path to the driver python module
optional arguments:
-h, --help            show this help …
```
=> Provide server address as a parameter from command line

rose/server/game.py, rose/web/game.js, rose/web/index.html
Fixes issue #263 
-  frontend: Enable the "Start" button only when at least one player is connected
- frontend: Render "No player connected" message if no player is connected.
- backend: fail start() if no player is connected
- backend: When a player disconnects, stop the game if it was the last player
=> Stop game if no players connected

docs/index.md, docs/materials.md, docs/meet_linux.md
This patch corrects the links appear on index.md, and also
creates materials.md, which will contain the course materials.
Each course topic will have its own page, which (supposed to) include the
presentation shown on class, home works, exercises and extras.
=> Correct links on index.md and create materials.md

rose/web/index.html
Previously encoding was unset, which resulted in an error in the console and potentially wrong encoding with various browsers.
=> Add UTF-8 encoding to HTML

.travis.yml
Since `python2.7` is no longer supported and AFAIK we have nothing in ROSE project
that needs to run with 2.7
=> Remove CI tests for python2.7

rose/server/score.py
The line's length is currently 80>79 chars.
This patch tries to fix it, so the Travis test won't fail.
=> score.py: avoid failing on flake8 test

.dockerignore, Dockerfile, README.md
Hi @sleviim @sfishbai , 
This pr is trying to follow the notes for #309 and raised the issue #427 .
One way of solving the issue is creating a requirements_dev.txt with the needed dependencies.
The question is, would you prefer to lock all the module versions or only `idna`(the conflicting one)?
=> Dockerfile for ROSE

README.md
Due to an issue encountered with fedora nodes we decided to move to venv instead of pipenv having that it is shipped with python and does not require any addtional installations
=> moved from pipenv to venv

classroom/connect_service.py
./classroom/connect_service.py:40:11: E275 missing whitespace after keyword
return(service)
^
1     E275 missing whitespace after keyword
=> Fix flake error

README.md
The default prefix-key is Ctrl-b
=> README: Fix and add some tmux commands

rose/web/game.js, rose/web/index.html
Submitted by Itay Hofshy, Avia Izakovitch, Gavriel Fernanadez.
why?
While working on our driver's code, we got confused many times by the "Play" button, since it seemed that this button starts the game, but it actually starts the music. We changed its name to "Music" so that the player will not get confused anymore.
Screenshots:
=> changed the Play button to Music button

rose/common/config.py, rose/server/score.py
Issue:
In our score code we use refactored logic that does not explicitly follow the documented rules.
For example, when calculating the players score we use negative logic, e.g. `player.action != actions.BRAKE`  , while in the documentation we define the rules using positive language, e.g. ` if you want to continue forward. return actions.RIGHT or actions.LEFT if you like to bypass the obstacle. `
There are reasons why you might want to follow the document's logic explicitly rather than refactoring it:
- Clarity and Traceability: If someone else (or even you at a later time) refers back to the original documentation to understand or validate the code's behavior, having the logic implemented as closely as possible to the documented rules makes it easier to follow and validate.
- Avoid …
=> Use positive logic when calculating score

rose/server/score.py, rose/server/score_test.py
Looks like the documentation does not describe the rules of the game correctly. Add debug logs to make it easier to understand the scoring loop and its semantics.
To see the new logs we need to enable debug level logging. In the test this can be done like this:
pytest --log-cli-level=debug
Example logs from the collisions tests:
```
rose/server/score_test.py::TestCollisions::test_player_in_lane_wins 
-------------------------------- live log call ---------------------------------
INFO     score:score.py:113 process_actions: name=A lane=0 pos=1,5 score=10 response_time=1.000000
DEBUG    score:score.py:87 player B picked up penguin: got 10 points
INFO     score:score.py:113 process_actions: name=B lane=1 pos=1,6 score=20 response_time=1.000000
PASSED …
```
=> Add debug logging to score module

rose/server/player.py, rose/server/player_test.py
Issue:
When testing if a car is in lane, we do an implicit test, calculating the start and end x value of the player lane, it's better to use explicit calculation to get the lane directly from car position.
=> Explictly test for players car in lane
